In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("./combined-dataset.csv")
feature_list = dataset.columns.values
dataset

c:\Users\91884\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (2,3,5,6,7,8,11,14,15,16,17,22,23,27,28,31,32,34,35,45,47,48,51,54,55) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


frame.time    ip.src_host    ip.dst_host  \
0        2021 11:35:29.350784000   192.168.0.170  192.168.0.128   
1        2021 11:35:29.366808000   192.168.0.170  192.168.0.128   
2        2021 11:35:29.383006000   192.168.0.170  192.168.0.128   
3        2021 11:35:29.399136000   192.168.0.170  192.168.0.128   
4        2021 11:35:29.418619000   192.168.0.170  192.168.0.128   
...                           ...            ...            ...   
773789   2021 13:28:33.093838000   192.168.0.128  192.168.0.101   
773790   2021 13:28:33.097063000   192.168.0.101  192.168.0.128   
773791   2021 13:28:33.097104000   192.168.0.128  192.168.0.101   
773792   2021 13:28:33.097473000   192.168.0.128  192.168.0.101   
773793                                      NaN            NaN   

       arp.dst.proto_ipv4  arp.opcode arp.hw.size arp.src.proto_ipv4  \
0                       0         0.0           0                  0   
1                       0         0.0           0                  0   
2                       0         0.0           0                  0   
3                       0         0.0           0                  0   
4                       0         0.0           0                  0   
...                   ...         ...         ...                ...   
773789                  0         0.0           0                  0   
773790                  0         0.0           0                  0   
773791                  0         0.0           0                  0   
773792                  0         0.0           0                  0   
773793                NaN         NaN         NaN                NaN   

       icmp.checksum icmp.seq_le  icmp.transmit_timestamp  ...  \
0                  0           0                      0.0  ...   
1                  0           0                      0.0  ...   
2                  0           0                      0.0  ...   
3                  0           0                      0.0  ...   
4                  0           0                      0.0  ...   
...              ...         ...                      ...  ...   
773789             0           0                      0.0  ...   
773790             0           0                      0.0  ...   
773791             0           0                      0.0  ...   
773792             0           0                      0.0  ...   
773793           NaN         NaN                      NaN  ...   

        mqtt.proto_len mqtt.protoname  mqtt.topic  mqtt.topic_len mqtt.ver  \
0                  0.0              0           0             0.0      0.0   
1                  0.0              0           0             0.0      0.0   
2                  0.0              0           0             0.0      0.0   
3                  0.0              0           0             0.0      0.0   
4                  0.0              0           0             0.0      0.0   
...                ...            ...         ...             ...      ...   
773789             0.0              0           0             0.0      0.0   
773790             4.0           MQTT           0             0.0      4.0   
773791             0.0              0           0             0.0      0.0   
773792             0.0              0           0             0.0      0.0   
773793             NaN            NaN         NaN             NaN      NaN   

       mbtcp.len mbtcp.trans_id mbtcp.unit_id  Attack_label  Attack_type  
0            0.0            0.0           0.0           1.0    DDoS_HTTP  
1            0.0            0.0           0.0           1.0    DDoS_HTTP  
2            0.0            0.0           0.0           1.0    DDoS_HTTP  
3            0.0            0.0           0.0           1.0    DDoS_HTTP  
4            0.0            0.0           0.0           1.0    DDoS_HTTP  
...          ...            ...           ...           ...          ...  
773789       0.0            0.0           0.0           0.0       Normal  
773790       0.0       

In [3]:
feature_list

array(['frame.time', 'ip.src_host', 'ip.dst_host', 'arp.dst.proto_ipv4',
       'arp.opcode', 'arp.hw.size', 'arp.src.proto_ipv4', 'icmp.checksum',
       'icmp.seq_le', 'icmp.transmit_timestamp', 'icmp.unused',
       'http.file_data', 'http.content_length', 'http.request.uri.query',
       'http.request.method', 'http.referer', 'http.request.full_uri',
       'http.request.version', 'http.response', 'http.tls_port',
       'tcp.ack', 'tcp.ack_raw', 'tcp.checksum', 'tcp.connection.fin',
       'tcp.connection.rst', 'tcp.connection.syn',
       'tcp.connection.synack', 'tcp.dstport', 'tcp.flags',
       'tcp.flags.ack', 'tcp.len', 'tcp.options', 'tcp.payload',
       'tcp.seq', 'tcp.srcport', 'udp.port', 'udp.stream',
       'udp.time_delta', 'dns.qry.name', 'dns.qry.name.len', 'dns.qry.qu',
       'dns.qry.type', 'dns.retransmission', 'dns.retransmit_request',
       'dns.retransmit_request_in', 'mqtt.conack.flags',
       'mqtt.conflag.cleansess', 'mqtt.conflags', 'mqtt.hdrflags',
  

In [4]:
dataset = dataset.drop(columns=['frame.time','ip.src_host','ip.dst_host'])

In [5]:
dataset

arp.dst.proto_ipv4  arp.opcode arp.hw.size arp.src.proto_ipv4  \
0                       0         0.0           0                  0   
1                       0         0.0           0                  0   
2                       0         0.0           0                  0   
3                       0         0.0           0                  0   
4                       0         0.0           0                  0   
...                   ...         ...         ...                ...   
773789                  0         0.0           0                  0   
773790                  0         0.0           0                  0   
773791                  0         0.0           0                  0   
773792                  0         0.0           0                  0   
773793                NaN         NaN         NaN                NaN   

       icmp.checksum icmp.seq_le  icmp.transmit_timestamp  icmp.unused  \
0                  0           0                      0.0          0.0   
1                  0           0                      0.0          0.0   
2                  0           0                      0.0          0.0   
3                  0           0                      0.0          0.0   
4                  0           0                      0.0          0.0   
...              ...         ...                      ...          ...   
773789             0           0                      0.0          0.0   
773790             0           0                      0.0          0.0   
773791             0           0                      0.0          0.0   
773792             0           0                      0.0          0.0   
773793           NaN         NaN                      NaN          NaN   

       http.file_data  http.content_length  ...  mqtt.proto_len  \
0                   0                  0.0  ...             0.0   
1                   0                  0.0  ...             0.0   
2                   0                  0.0  ...             0.0   
3                   0                  0.0  ...             0.0   
4                   0                  0.0  ...             0.0   
...               ...                  ...  ...             ...   
773789              0                  0.0  ...             0.0   
773790              0                  0.0  ...             4.0   
773791              0                  0.0  ...             0.0   
773792              0                  0.0  ...             0.0   
773793            NaN                  NaN  ...             NaN   

       mqtt.protoname mqtt.topic mqtt.topic_len mqtt.ver  mbtcp.len  \
0                   0          0            0.0      0.0        0.0   
1                   0          0            0.0      0.0        0.0   
2                   0          0            0.0      0.0        0.0   
3                   0          0            0.0      0.0        0.0   
4                   0          0            0.0      0.0        0.0   
...               ...        ...            ...      ...        ...   
773789              0          0            0.0      0.0        0.0   
773790           MQTT          0            0.0      4.0        0.0   
773791              0          0            0.0      0.0        0.0   
773792              0          0            0.0      0.0        0.0   
773793            NaN        NaN            NaN      NaN        NaN   

        mbtcp.trans_id  mbtcp.unit_id  Attack_label Attack_type  
0                  0.0            0.0           1.0   DDoS_HTTP  
1                  0.0            0.0           1.0   DDoS_HTTP  
2                  0.0            0.0           1.0   DDoS_HTTP  
3                  0.0            0.0           1.0   DDoS_HTTP  
4                  0.0            0.0           1.0   DDoS_HTTP  
...                ...            ...           ...         ...  
773789             0.0            0.0           0.0      Normal  
773790             0.0            0.0           0.0      Normal  
7

In [6]:
dataset = dataset.drop(index=dataset.index[-1])

In [7]:
dataset

arp.dst.proto_ipv4  arp.opcode arp.hw.size arp.src.proto_ipv4  \
0                       0         0.0           0                  0   
1                       0         0.0           0                  0   
2                       0         0.0           0                  0   
3                       0         0.0           0                  0   
4                       0         0.0           0                  0   
...                   ...         ...         ...                ...   
773788                  0         0.0           0                  0   
773789                  0         0.0           0                  0   
773790                  0         0.0           0                  0   
773791                  0         0.0           0                  0   
773792                  0         0.0           0                  0   

       icmp.checksum icmp.seq_le  icmp.transmit_timestamp  icmp.unused  \
0                  0           0                      0.0          0.0   
1                  0           0                      0.0          0.0   
2                  0           0                      0.0          0.0   
3                  0           0                      0.0          0.0   
4                  0           0                      0.0          0.0   
...              ...         ...                      ...          ...   
773788             0           0                      0.0          0.0   
773789             0           0                      0.0          0.0   
773790             0           0                      0.0          0.0   
773791             0           0                      0.0          0.0   
773792             0           0                      0.0          0.0   

       http.file_data  http.content_length  ...  mqtt.proto_len  \
0                   0                  0.0  ...             0.0   
1                   0                  0.0  ...             0.0   
2                   0                  0.0  ...             0.0   
3                   0                  0.0  ...             0.0   
4                   0                  0.0  ...             0.0   
...               ...                  ...  ...             ...   
773788              0                  0.0  ...             0.0   
773789              0                  0.0  ...             0.0   
773790              0                  0.0  ...             4.0   
773791              0                  0.0  ...             0.0   
773792              0                  0.0  ...             0.0   

       mqtt.protoname mqtt.topic mqtt.topic_len mqtt.ver  mbtcp.len  \
0                   0          0            0.0      0.0        0.0   
1                   0          0            0.0      0.0        0.0   
2                   0          0            0.0      0.0        0.0   
3                   0          0            0.0      0.0        0.0   
4                   0          0            0.0      0.0        0.0   
...               ...        ...            ...      ...        ...   
773788              0          0            0.0      0.0        0.0   
773789              0          0            0.0      0.0        0.0   
773790           MQTT          0            0.0      4.0        0.0   
773791              0          0            0.0      0.0        0.0   
773792              0          0            0.0      0.0        0.0   

        mbtcp.trans_id  mbtcp.unit_id  Attack_label Attack_type  
0                  0.0            0.0           1.0   DDoS_HTTP  
1                  0.0            0.0           1.0   DDoS_HTTP  
2                  0.0            0.0           1.0   DDoS_HTTP  
3                  0.0            0.0           1.0   DDoS_HTTP  
4                  0.0            0.0           1.0   DDoS_HTTP  
...                ...            ...           ...         ...  
773788             0.0            0.0           0.0      Normal  
773789             0.0            0.0           0.0      Normal  
7

In [8]:
dataset.shape  
dataset = dataset.replace(np.inf,np.nan)    # replacing inf with nan
dataset = dataset.fillna(dataset.mean(numeric_only=True)) # then converting nan to mean values

In [11]:
dataset

arp.dst.proto_ipv4  arp.opcode arp.hw.size arp.src.proto_ipv4  \
0                       0         0.0           0                  0   
1                       0         0.0           0                  0   
2                       0         0.0           0                  0   
3                       0         0.0           0                  0   
4                       0         0.0           0                  0   
...                   ...         ...         ...                ...   
773788                  0         0.0           0                  0   
773789                  0         0.0           0                  0   
773790                  0         0.0           0                  0   
773791                  0         0.0           0                  0   
773792                  0         0.0           0                  0   

       icmp.checksum icmp.seq_le  icmp.transmit_timestamp  icmp.unused  \
0                  0           0                      0.0          0.0   
1                  0           0                      0.0          0.0   
2                  0           0                      0.0          0.0   
3                  0           0                      0.0          0.0   
4                  0           0                      0.0          0.0   
...              ...         ...                      ...          ...   
773788             0           0                      0.0          0.0   
773789             0           0                      0.0          0.0   
773790             0           0                      0.0          0.0   
773791             0           0                      0.0          0.0   
773792             0           0                      0.0          0.0   

       http.file_data  http.content_length  ...  mqtt.proto_len  \
0                   0                  0.0  ...             0.0   
1                   0                  0.0  ...             0.0   
2                   0                  0.0  ...             0.0   
3                   0                  0.0  ...             0.0   
4                   0                  0.0  ...             0.0   
...               ...                  ...  ...             ...   
773788              0                  0.0  ...             0.0   
773789              0                  0.0  ...             0.0   
773790              0                  0.0  ...             4.0   
773791              0                  0.0  ...             0.0   
773792              0                  0.0  ...             0.0   

       mqtt.protoname mqtt.topic mqtt.topic_len mqtt.ver  mbtcp.len  \
0                   0          0            0.0      0.0        0.0   
1                   0          0            0.0      0.0        0.0   
2                   0          0            0.0      0.0        0.0   
3                   0          0            0.0      0.0        0.0   
4                   0          0            0.0      0.0        0.0   
...               ...        ...            ...      ...        ...   
773788              0          0            0.0      0.0        0.0   
773789              0          0            0.0      0.0        0.0   
773790           MQTT          0            0.0      4.0        0.0   
773791              0          0            0.0      0.0        0.0   
773792              0          0            0.0      0.0        0.0   

        mbtcp.trans_id  mbtcp.unit_id  Attack_label Attack_type  
0                  0.0            0.0           1.0   DDoS_HTTP  
1                  0.0            0.0           1.0   DDoS_HTTP  
2                  0.0            0.0           1.0   DDoS_HTTP  
3                  0.0            0.0           1.0   DDoS_HTTP  
4                  0.0            0.0           1.0   DDoS_HTTP  
...                ...            ...           ...         ...  
773788             0.0            0.0           0.0      Normal  
773789             0.0            0.0           0.0      Normal  
7

In [12]:
dataset = dataset.drop(columns=['Attack_label'])

In [13]:
dataset

arp.dst.proto_ipv4  arp.opcode arp.hw.size arp.src.proto_ipv4  \
0                       0         0.0           0                  0   
1                       0         0.0           0                  0   
2                       0         0.0           0                  0   
3                       0         0.0           0                  0   
4                       0         0.0           0                  0   
...                   ...         ...         ...                ...   
773788                  0         0.0           0                  0   
773789                  0         0.0           0                  0   
773790                  0         0.0           0                  0   
773791                  0         0.0           0                  0   
773792                  0         0.0           0                  0   

       icmp.checksum icmp.seq_le  icmp.transmit_timestamp  icmp.unused  \
0                  0           0                      0.0          0.0   
1                  0           0                      0.0          0.0   
2                  0           0                      0.0          0.0   
3                  0           0                      0.0          0.0   
4                  0           0                      0.0          0.0   
...              ...         ...                      ...          ...   
773788             0           0                      0.0          0.0   
773789             0           0                      0.0          0.0   
773790             0           0                      0.0          0.0   
773791             0           0                      0.0          0.0   
773792             0           0                      0.0          0.0   

       http.file_data  http.content_length  ...  mqtt.msgtype mqtt.proto_len  \
0                   0                  0.0  ...           0.0            0.0   
1                   0                  0.0  ...           0.0            0.0   
2                   0                  0.0  ...           0.0            0.0   
3                   0                  0.0  ...           0.0            0.0   
4                   0                  0.0  ...           0.0            0.0   
...               ...                  ...  ...           ...            ...   
773788              0                  0.0  ...           0.0            0.0   
773789              0                  0.0  ...           0.0            0.0   
773790              0                  0.0  ...           1.0            4.0   
773791              0                  0.0  ...           0.0            0.0   
773792              0                  0.0  ...           2.0            0.0   

       mqtt.protoname mqtt.topic mqtt.topic_len  mqtt.ver  mbtcp.len  \
0                   0          0            0.0       0.0        0.0   
1                   0          0            0.0       0.0        0.0   
2                   0          0            0.0       0.0        0.0   
3                   0          0            0.0       0.0        0.0   
4                   0          0            0.0       0.0        0.0   
...               ...        ...            ...       ...        ...   
773788              0          0            0.0       0.0        0.0   
773789              0          0            0.0       0.0        0.0   
773790           MQTT          0            0.0       4.0        0.0   
773791              0          0            0.0       0.0        0.0   
773792              0          0            0.0       0.0        0.0   

        mbtcp.trans_id  mbtcp.unit_id Attack_type  
0                  0.0            0.0   DDoS_HTTP  
1                  0.0            0.0   DDoS_HTTP  
2                  0.0            0.0   DDoS_HTTP  
3                  0.0            0.0   DDoS_HTTP  
4                  0.0            0.0   DDoS_HTTP  
...                ...            ...         ...  
773788             0.0            0.0      Normal  
773789     

In [14]:
X = dataset.iloc[:,:-1].values
print("shape of X",X.shape)

Y = dataset.iloc[:,-1].values
print("shape of Y",Y.shape)

shape of X (773793, 58)
shape of Y (773793,)


In [16]:
X

array([[0, 0.0, 0, ..., 0.0, 0.0, 0.0],
       [0, 0.0, 0, ..., 0.0, 0.0, 0.0],
       [0, 0.0, 0, ..., 0.0, 0.0, 0.0],
       ...,
       ['0', 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ['0', 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ['0', 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [25]:
Y

array(['DDoS_HTTP', 'DDoS_HTTP', 'DDoS_HTTP', ..., 'Normal', 'Normal',
       'Normal'], dtype=object)

In [26]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y= LabelEncoder()  
Y = labelencoder_y.fit_transform(Y) 

In [27]:
Y

array([0, 0, 0, ..., 5, 5, 5])

In [28]:
np.unique(Y)

array([0, 1, 2, 3, 4, 5, 6])

In [29]:
print(Y)

[0 0 0 ... 5 5 5]


In [30]:
np.isin(6,Y)

array(True)

In [35]:
print("is NaN present:",np.any(pd.isna(X)))  # to check whether the array contains nan
#print("is inf present:",np.any(pd.isinf(X)))  # to check whether the array contains inf
#X[X < 0] = 0   # to replace all negative values with zeros

is NaN present: False


In [36]:
from sklearn.feature_selection import SelectKBest  # feature selection
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif

In [40]:
X

array([[0, 0.0, 0, ..., 0.0, 0.0, 0.0],
       [0, 0.0, 0, ..., 0.0, 0.0, 0.0],
       [0, 0.0, 0, ..., 0.0, 0.0, 0.0],
       ...,
       ['0', 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ['0', 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ['0', 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [42]:
Y.dtype

dtype('int32')

In [43]:
X.dtype

dtype('O')

In [47]:
row_indices = np.where(X == '192.168.0.128')[0]
print(row_indices)

[ 30735  30736  73586 ... 760426 760507 760508]


In [64]:
X[X == '192.168.0.147'] = 0

In [65]:
X = X.astype(int)

ValueError: invalid literal for int() with base 10: '192.168.0.101'